{{ config(materialized='table') }}

SELECT
    quote_id,
    policy_id,
    event_date,
    generated_timestamp_utc,
    account_name,
    country,
    iso_code,
    region,
    city,
    latitude,
    longitude,
    asset_type,
    peril,
    hazard_score,
    hazard_level,
    risk_category,
    insured_value_usd,
    pricing_variant,
    quoted_premium_usd,
    expected_loss_usd,
    bound_flag,
    bound_status,
    risk_weight,
    risk_weighted_value_usd,
    premium_rate,
    expected_loss_ratio,
    event_month
FROM databricks_learning_premium.default.gold_exposure_events_engineering